### ISSUE TITLE
Feature: compile via a docker container

### ISSUE THREAD

**Issue by mattscilipoti** [zcalusic/sysinfo#25]
Are you interested in providing the ability to compile via a docker container? I would be happy to work with you to incorporate what I did at https://github.com/mattscilipoti/compile_sysinfo. I tried to share architectural decisions in the readme, but I'm happy to discuss anytime.

**Comment by zcalusic** [comment]
Hello @mattscilipoti and thanks for your contribution! Also, sorry for a late reply, so little free time these days...

To be honest, I'd rather keep these two repos separate, so that this one remains a very simple Go library. This also has a benefit that maintaining each repo is simpler, no need for PR's, reviews etc...

Generally, I find that various people like their containers built a little bit differently, so let's not pressure any "right" way to do it. Even I have dockerfiles repo, and yes, many times I override upstream ideas how to pack something into container.

But, of course, I'll add a pointer to your repo in the README, so it's easier to find. I'll do it right away.
